---
- name: Install dependencies
  package: name={{item}} state=latest
  become: yes
  with_items:
    - git

- name: Install rbenv
  become: yes
  become_user: "{{ rbenv.user }}"
  git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv

- name: Add ~/.rbenv/bin to PATH
  become: yes
  become_user: "{{ rbenv.user }}"
  lineinfile: >
    dest="~/.profile"
    line="export PATH=$HOME/.rbenv/bin:$PATH"

- name: Eval rbenv init in ~/.profile
  become: yes
  become_user: "{{ rbenv.user }}"
  lineinfile: >
    dest="~/.profile"
    line='eval "$(rbenv init -)a"'

- name: Install dependencies for ruby-build (see. https://github.com/sstephenson/ruby-build/wiki)
  package: name={{ item }} state=latest
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev
 
- name: Install ruby-build as rbenv plugin
  become: yes
  become_user: "{{ rbenv.user }}"
  git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build

- name: Check if version is installed ruby
  become: yes
  become_user: "{{ rbenv.user }}"
  shell: bash -lc "rbenv versions | grep {{ rbenv.ruby_version }}"
  register: rbenv_check_install
  changed_when: False
  ignore_errors: yes

- name: Install ruby
  become: yes
  become_user: "{{ rbenv.user }}"
  shell: bash -lc "rbenv install {{ rbenv.ruby_version }}"
  when: rbenv_check_install|failed

- name: Check if version is the default ruby version
  become: yes
  become_user: "{{ rbenv.user }}"
  shell: bash -lc "rbenv version | grep {{ rbenv.ruby_version }}"
  register: rbenv_check_default
  changed_when: False
  ignore_errors: yes

- name: Set default ruby version
  become: yes
  become_user: "{{ rbenv.user }}"
  shell: bash -lc "rbenv global {{ rbenv.ruby_version }}"
  when: rbenv_check_default|failed
 
- name: Copy .gemrc
  become: yes
  become_user: "{{ rbenv.user }}"
  copy: src="_gemrc" dest="~/.gemrc"

- name: Install bundler
  become: yes
  become_user: "{{ rbenv.user }}"
  shell: bash -lc "gem install bundler"
  when: rbenv_check_default|failed
